#!/usr/bin/env bash
set -e
cd "$(dirname "$0")/.."

# Clone only if the folder doesn't exist
if [[ ! -d "core" ]]; then
    git clone --depth 1 --branch dev https://github.com/home-assistant/core.git
fi

pip3 install \
    colorlog==6.7.0 \
    ruff==0.0.265

./scripts/setup-dependencies
./scripts/setup-symlinks
pre-commit install-hooks
