#!/usr/bin/env bash
set -ex
cd "$(dirname "$0")/.."

# Link custom components
cd core/homeassistant/components/
ln -fs ../../../custom_components/bhyve bhyve
cd -

# Link tests
cd core/tests/components/
ln -fs ../../../tests/ bhyve
cd -